services:
  frontend:
    build:
      context: .
      target: frontend
    container_name: soundowl-frontend
    command: npm --prefix frontend start
    environment:
      FRONTEND_HOST: 0.0.0.0
      FRONTEND_PORT: 8081
      FRONTEND_CONFIG_PATH: /app/frontend/config/frontend-settings.json
      FRONTEND_BACKEND_SERVER_DEFAULT: ${BACKEND_SERVER_URL:-http://192.168.0.135:3000/}
    ports:
      - "80:8081"
    volumes:
      - ./frontend/config:/app/frontend/config
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      target: backend
    container_name: soundowl-backend
    command: node backend-node/src/server.js
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      WEBSOCKET_HOST: 0.0.0.0
      WEBSOCKET_PORT: 8080
      DB_SERVER: soundowl-db
      DB_NAME: sound
      DB_USER: root
      DB_PASSWORD: sound
      REDIS_SERVER: soundowl-redis
      SOUND_PATH: /music
      SETTINGS_PATH: /app/backend-node/config/settings.json
      CORS_ALLOW_ORIGINS: "*"
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ${MUSIC_DIR:-./music}:/music
      - ./audio_pulse:/app/audio_pulse
      - ./backend-node/config:/app/backend-node/config
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: mariadb:11
    container_name: soundowl-db
    environment:
      MYSQL_ROOT_PASSWORD: sound
      MYSQL_DATABASE: sound
      MYSQL_USER: sound
      MYSQL_PASSWORD: sound
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    hostname: soundowl-db
    restart: always
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
      - ./parts/setup/db/soundowl_table_mysql.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    container_name: soundowl-redis
    hostname: soundowl-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  redis_data:
