version: "3"
services:
  web:
    build: .
    volumes:
      - ${MUSIC_DIR}:/music
    ports:
      - "80:80"
    environment:
      REDIS_SERVER: soundowl-redis
      DB_SERVER: soundowl-db
    depends_on:
      - db
      - redis
      - websocket
      - que
  db:
    image: mariadb
    container_name: soundowl-db
    environment:
      MYSQL_ROOT_PASSWORD: sound
      MYSQL_DATABASE: sound
      MYSQL_USER: sound
      MYSQL_PASSWORD: sound
    ports:
      - target: 3306
        protocol: tcp
        mode: host
    volumes:
      - db_data:/var/lib/mysql
      - ./parts/setup/db/soundowl_table_mysql.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: soundowl-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  websocket:
    build: .
    command: php /var/www/html/api/sw/server.php
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  que:
    build: .
    command: php /var/www/html/api/quescript/queueAction.php
    depends_on:
      - db
      - redis
volumes:
  db_data:
