version: "3"
services:
  web:
    build: .
    volumes:
      - ${MUSIC_DIR}:/music
      - ./api/lock:/var/www/html/api/lock
      - ./parts/setting.ini:/var/www/html/parts/setting.ini
    ports:
      - "80:80"
    environment:
      REDIS_SERVER: soundowl-redis
      DB_SERVER: soundowl-db
      SOUND_PATH: /music
    networks:
      - app-network
    depends_on:
      - db
      - redis
      - websocket
      - que

  db:
    image: mariadb
    container_name: soundowl-db
    environment:
      MYSQL_ROOT_PASSWORD: sound
      MYSQL_DATABASE: sound
      MYSQL_USER: sound
      MYSQL_PASSWORD: sound
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306/tcp"
    hostname: soundowl-db
    restart: always
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
      - ./parts/setup/db/soundowl_table_mysql.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: soundowl-redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - "./data/redis:/data"

  websocket:
    build: .
    command: php /var/www/html/api/sw/server.php
    ports:
      - "8080:8080"
    volumes:
      - ./api/lock:/var/www/html/api/lock
      - ./parts/setting.ini:/var/www/html/parts/setting.ini
    environment:
      REDIS_SERVER: soundowl-redis
      DB_SERVER: soundowl-db
      SOUND_PATH: /music
    networks:
      - app-network
    depends_on:
      - db
      - redis

  que:
    build: .
    command: php /var/www/html/api/quescript/queueAction.php
    volumes:
      - ${MUSIC_DIR}:/music
      - ./api/lock:/var/www/html/api/lock
      - ./parts/setting.ini:/var/www/html/parts/setting.ini
    environment:
      REDIS_SERVER: soundowl-redis
      DB_SERVER: soundowl-db
      SOUND_PATH: /music
    networks:
      - app-network
    depends_on:
      - db
      - redis

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
