openapi: 3.0.0
info:
  title: SoundOwl
  version: 1.0.0
paths:
  /api/albums/playcount/desc:
    get:
      summary: Get a list of albums sorted by play count in descending order
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      description: The title of the album
                    albumKey:
                      type: string
                      description: A compressed key representing the album