name: Docker Image CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:

  build-and-test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: Build Docker image
      run: docker build -t soundowl .
    - name: List files
      run: ls -la
    - name: Run tests
      run: docker-compose up -d
      env:
        MUSIC_DIR: './music/'
