name: Docker Image CI

on:
  push:
    paths: ["backend-node/**", "parts/**", ".github/workflows/docker-image.yml", "Dockerfile", "docker-compose.yml"]
  pull_request:
    paths: ["backend-node/**", "parts/**", ".github/workflows/docker-image.yml", "Dockerfile", "docker-compose.yml"]

permissions:
  contents: read

jobs:
  webpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build and Test Webpack
        uses: ./.github/workflows/webpack.yml

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Build Docker image
      run: docker build -t soundowl .
    - name: List files
      run: ls -la
    - name: Run tests
      run: docker compose up -d db redis backend frontend
      env:
        MUSIC_DIR: './music/'
