name: Soundowl Docker Image Build and Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  frontend-build:
    uses: ./.github/workflows/webpack.yml
  
  backend-contract-test:
    uses: ./.github/workflows/backend-contract.yml
  
  sql-setup:
    uses: ./.github/workflows/mariadb.yml

  build-and-test:
    needs: [frontend-build, backend-contract-test, sql-setup]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Build Docker image
      run: docker build -t soundowl .
    - name: List files
      run: ls -la
    - name: Run tests
      run: docker compose up -d db redis backend frontend
      env:
        MUSIC_DIR: './music/'
