name: Frontend Server Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  start-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install server dependencies
      run: npm install

    - name: Install and build frontend
      run: |
        cd frontend
        npm ci
        npm run build

    - name: Start server and check
      run: |
        node server.js &
        SERVER_PID=$!
        for i in {1..15}; do
          if curl -s http://localhost:3000/ | grep -q '<body id="app">'; then
            echo "Server responded"
            kill $SERVER_PID
            exit 0
          fi
          sleep 2
        done
        echo "Server failed"
        kill $SERVER_PID
        exit 1

