name: MariaDB Table Setup Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - name: Copy SQL script to MariaDB container
        run: docker cp parts/setup/db/soundowl_table_mysql.sql ${{ job.services.mariadb.id }}:/soundowl_table_mysql.sql

      - name: Run SQL script inside MariaDB container
        run: docker exec ${{ job.services.mariadb.id }} mysql -h localhost -u root -ppassword testdb < /soundowl_table_mysql.sql
