name: MariaDB Table Setup Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4
      - name: PS
        run: |
          docker ps
      - name: Run SQL script
        run: |
          mysql -h mariadb --port 3306 -u root -ppassword testdb < parts/setup/db/soundowl_table_mysql.sql
