name: MariaDB Initial SQL Test

on:
  push:
  pull_request:

jobs:
  test-mariadb:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.5
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_db

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Wait for MariaDB to be ready
      run: |
        retries=30
        while [ $retries -gt 0 ]; do
          if docker exec $(docker ps -q -f name=mariadb) mysqladmin ping -uroot -proot_password --silent; then
            echo "MariaDB is up and running!"
            break
          fi
          echo "Waiting for MariaDB to be ready..."
          sleep 10
          retries=$((retries - 1))
        done
        if [ $retries -eq 0 ]; then
          echo "MariaDB did not become ready in time."
          docker logs $(docker ps -q -f name=mariadb)
          exit 1
        fi

    - name: Apply initial SQL
      run: |
        docker exec -i $(docker ps -q -f name=mariadb) mysql -uroot -proot_password test_db < parts/setup/db/soundowl_table_mysql.sql

    - name: Verify tables
      run: |
        docker exec $(docker ps -q -f name=mariadb) mysql -uroot -proot_password -D test_db -e "SHOW TABLES;"

    - name: Verify procedures
      run: |
        docker exec $(docker ps -q -f name=mariadb) mysql -uroot -proot_password -D test_db -e "SHOW PROCEDURE STATUS WHERE Db = 'test_db';"

    - name: Verify events
      run: |
        docker exec $(docker ps -q -f name=mariadb) mysql -uroot -proot_password -D test_db -e "SHOW EVENTS;"

    - name: Insert test data
      run: |
        docker exec -i $(docker ps -q -f name=mariadb) mysql -uroot -proot_password test_db <<EOF
        INSERT INTO sound_play_history (sound_hash, play_date) VALUES
          ('hash1', '2023-01-01'),
          ('hash2', '2023-02-01'),
          ('hash3', '2023-03-01');
        EOF

    - name: Run manage_partitions_and_compact_ids procedure
      run: |
        docker exec $(docker ps -q -f name=mariadb) mysql -uroot -proot_password -D test_db -e "CALL manage_partitions_and_compact_ids();"

    - name: Verify partitions
      run: |
        docker exec $(docker ps -q -f name=mariadb) mysql -uroot -proot_password -D test_db -e "SELECT PARTITION_NAME FROM INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_SCHEMA = 'test_db' AND TABLE_NAME = 'sound_play_history';"

    - name: Verify ID compaction
      run: |
        docker exec $(docker ps -q -f name=mariadb) mysql -uroot -proot_password -D test_db -e "SELECT * FROM sound_play_history ORDER BY id;"
