name: MariaDB Initial SQL Test

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  test-mariadb:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      MYSQL:   mysql   -h 127.0.0.1 -P 3306 -uroot -proot_password
      MYSQLADM: mysqladmin -h 127.0.0.1 -P 3306 -uroot -proot_password

    steps:
    - uses: actions/checkout@v2

    - name: Wait until MariaDB responds
      run: |
        for i in {1..60}; do
          $MYSQLADM ping --silent && { echo "MariaDB ready"; exit 0; }
          sleep 5
        done
        echo "MariaDB not ready" && exit 1

    - name: Apply initial SQL
      run: $MYSQL test_db < parts/setup/db/soundowl_table_mysql.sql

    - name: Enable event scheduler & grant privilege
      run: |
        $MYSQL    -e "SET GLOBAL event_scheduler = ON;"
        $MYSQL    -e "GRANT EVENT ON *.* TO 'root'@'%'; FLUSH PRIVILEGES;"

    # ───────── オブジェクト検証 ─────────
    - name: Verify objects
      run: |
        extract() { grep -oP "$1" parts/setup/db/soundowl_table_mysql.sql; }

        tables=$(   extract '^CREATE TABLE `\K[^`]+(?=`)' )
        procs=$(    extract '^CREATE PROCEDURE (?:`)?\K\w+' )
        events=$(   extract '^CREATE EVENT (?:IF NOT EXISTS )?(?:`)?\K\w+' )
        triggers=$( extract '^CREATE TRIGGER (?:`)?\K\w+' )
        views=$(    extract '^CREATE VIEW (?:`)?\K\w+' )

        check () {   # $1=SQL、$2=種類、$3=期待リスト
          act=$($MYSQL -N -e "$1")
          for n in $3; do echo "$act" | grep -qw "$n" || { echo "$2 $n is missing"; exit 1; }; done
        }

        check "SHOW TABLES FROM test_db;"                               table   "$tables"
        check "SHOW PROCEDURE STATUS WHERE Db='test_db';"              proc    "$procs"
        check "SHOW EVENTS FROM test_db;"                              event   "$events"
        check "SHOW TRIGGERS FROM test_db;"                            trigger "$triggers"
        check "SHOW FULL TABLES FROM test_db WHERE Table_type='VIEW';"  view    "$views"

    - name: Run manage_partitions_and_compact_ids & final checks
      run: |
        $MYSQL -D test_db -e "CALL manage_partitions_and_compact_ids();"
        $MYSQL -D test_db -e "SELECT PARTITION_NAME FROM INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_SCHEMA='test_db' AND TABLE_NAME='sound_play_history';"
        $MYSQL -D test_db -e "SELECT COUNT(*) AS rows_after_compaction FROM sound_play_history;"
