name: MySQL Initial SQL Test

on:
  push:
  pull_request:

jobs:
  test-mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_db

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Wait for MySQL to be ready
      run: |
        retries=30
        while [ $retries -gt 0 ]; do
          if docker exec $(docker ps -q -f name=mysql) mysqladmin ping -uroot -proot_password --silent; then
            echo "MySQL is up and running!"
            break
          fi
          echo "Waiting for MySQL to be ready..."
          sleep 10
          retries=$((retries - 1))
        done
        if [ $retries -eq 0 ]; then
          echo "MySQL did not become ready in time."
          docker logs $(docker ps -q -f name=mysql)
          exit 1
        fi

    - name: Apply initial SQL
      run: |
        docker exec -i $(docker ps -q -f name=mysql) mysql -uroot -proot_password test_db < /parts/setup/db/soundowl_table_mysql.sql

    - name: Verify tables
      run: |
        docker exec $(docker ps -q -f name=mysql) mysql -uroot -proot_password -e "SHOW TABLES IN test_db;"
