name: NodeJS with Webpack

on:
  push:
    paths: ["frontend/**", ".github/workflows/webpack.yml"]
  pull_request:
    paths: ["frontend/**", ".github/workflows/webpack.yml"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x, 26.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        cd frontend
        npm ci
      
    - name : build
      run :  |
        cd frontend
        npx webpack --config webpack.config.js

    - name: upload js folder ${{ matrix.node-version }}
      uses: actions/upload-artifact@v4
      with:
        name: js-artifact-node-${{ matrix.node-version }}
        path: frontend
        retention-days: 3
